# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

addons:
  apt:
    packages:
      - openjdk-10-jdk
#      - graphviz

####

before_install:
  apt-get install software-properties-common
  add-apt-repository ppa:webupd8team/java
