# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:webupd8team/java'
    packages:
      - openjdk-10-jdk
      - graphviz

####
